# -*- coding: utf-8 -*-
"""prime_mycode.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDL0QIP3gO5qhcUEzdYZLfsIaCHKVzsr
"""

num=int(input("Enter integer:\n"))
if (num>1):
   for i in range(2,num):
      if (num%i==0):
         print("num is not prime\n")
         break
   else:
     print(num,"is a prime\n")
elif(num==1) or (num==0):
    print("you have entered either 0 or 1 which are not prime numbers\n")
else:
    print("you have entered negative number, decimal number or non numberic character,try again\n")

num=int(input("Enter integer:\n"))
#if(isinstance(num,int))==False:
#   print("Enter a positive integer, not decimal or negative integer\n")
if (num>1):
  if(num==2):
     print(num,"is a prime number\n")
  for i in range(2,num):
    if (num%i==0):
       print("num is not prime\n")
       break
    if (i==num-1):
       print(num,"is a prime\n")
elif(num==0 or num==1):
      print("you have entered either 0 or 1 which are not prime numbers\n")
else:
    print("you have entered negative number, decimal number or non numberic character,try again\n")

